media: "media"

content:
  - name: portfolio
    label: "Портфолио"
    type: collection
    path: "content/portfolio"
    filename: "{primary}.json"
    format: "json"
    view:
      fields: [ title_ru, date ]
      primary: title_en
      sort: [ date ]
      default:
        sort: date
        order: desc
    fields:
      - name: image
        label: "Изображение"
        type: image
      - name: date
        label: "Дата"
        type: date
      - name: title_en
        label: "Название (EN)"
        type: string
      - name: title_ru
        label: "Название (РУ)"
        type: string
      - name: description_en
        label: "Описание (EN)"
        type: text
      - name: description_ru
        label: "Описание (РУ)"
        type: text
  - name: status
    label: "Заказы: {primary}"
    type: file
    path: "content/status.json"
    format: "json"
    view:
      fields: [ isOpen, message_ru ]
      primary: isOpen
    fields:
      - name: isOpen
        label: "Заказы открыты"
        type: boolean
        required: true
        default: false
      - name: message_en
        label: "Комментарий (EN)"
        type: text
      - name: message_ru
        label: "Комментарий (РУ)"
        type: text