media: "media"

content:
  - name: arts
    label: "Арты"
    type: collection
    path: "content/portfolio"
    filename: "{primary}.json"
    format: "json"
    view:
      fields: [ image, title, date ]
      primary: title
      sort: [ date ]
      default:
        sort: date
        order: desc
    fields:
      - name: image
        label: "Изображение"
        type: image
      - name: date
        label: "Дата"
        type: date
      - name: title
        label: "Название"
        type: string
      - name: description
        label: "Описание"
        type: rich-text
  - name: orders
    label: "Заказы"
    type: collection
    path: "content/orders"
    filename: "{year}-{month}-{day}-{primary}.json"
    format: "json"
    view:
      fields: [ client, date, status ]
      primary: client
      default:
        sort: status
    fields:
      - name: client
        label: "Заказчик"
        type: string
      - name: date
        label: "Дата"
        type: date
      - name: status
        label: "Статус"
        type: select
        options:
          values: [ "В очереди", "В работе", "Готов" ]
  - name: status
    label: "Заказы (вкл/выкл)"
    type: file
    path: "content/status.json"
    format: "json"
    fields:
      - name: isOpen
        label: "Открыть заказы"
        type: boolean
        required: true
        default: false
      - name: message
        label: "Комментарий"
        type: rich-text
  - name: prices
    label: "Прайсы"
    type: file
    path: "content/prices.json"
    format: "json"
    fields:
      - name: prices
        label: "Прайсы"
        type: block
        list: true
        default: []
        blocks:
          - name: price
            label: "Прайс"
            fields:
              - name: title
                label: "Позиция"
                type: string
              - name: value
                label: "Цена"
                type: string
    # fields:
    #   - name: categories
    #     label: "Категории"
    #     type: block
    #     list: true
    #     default: []
        # blocks:
        #   - name: pricelist
        #     label: "Прайсы"
        #     fields:
        #       - name: title_en
        #         label: "Категория (EN)"
        #         type: string
        #       - name: title_ru
        #         label: "Категория (РУ)"
        #         type: string
        #       - name: prices
        #         label: "Прайсы"
        #         type: block
        #         list: true
        #         default: []
        #         blocks:
        #           - name: price
        #             label: "Прайс"
        #             fields:
        #               - name: title_en
        #                 label: "Позиция (EN)"
        #                 type: string
        #               - name: title_ru
        #                 label: "Позиция (РУ)"
        #                 type: string
        #               - name: usd
        #                 label: "$"
        #                 type: number 
  - name: socials
    label: "Соцсети"
    type: file
    path: "content/socials.json"
    format: "json"
    fields:
      - name: socials
        label: "Соцсети"
        type: block
        list: true
        blocks:
          - name: social
            label: "Соцсеть"
            fields:
              - name: title
                label: "Название"
                type: string
              - name: link
                label: "Ссылка"
                type: string