media: "media"

content:
  - name: portfolio
    label: "Арты"
    type: collection
    path: "content/portfolio"
    filename: "{year}-{month}-{day}-{hour}-{minute}-{second}-{primary}.json"
    format: "json"
    view:
      fields: [ image, title_ru, date ]
      primary: title_en
      sort: [ date ]
      default:
        sort: date
        order: desc
    fields:
      - name: image
        label: "Изображение"
        type: image
      - name: date
        label: "Дата"
        type: date
      - name: title_en
        label: "Название (EN)"
        type: string
      - name: title_ru
        label: "Название (РУ)"
        type: string
      - name: description_en
        label: "Описание (EN)"
        type: text
      - name: description_ru
        label: "Описание (РУ)"
        type: text
  - name: orders
    label: "Заказы"
    type: collection
    path: "content/orders"
    filename: "{year}-{month}-{day}-{hour}-{minute}-{second}-{primary}.json"
    format: "json"
    fields:
      - name: client
        label: "Заказчик"
        type: string
      - name: date
        label: "Дата создания"
        type: date
      - name: status
        label: "Статус"
        type: select
        options:
          values: [ "В очереди", "В работе", "Готов" ]
  - name: status
    label: "Заказы (вкл/выкл)"
    type: file
    path: "content/status.json"
    format: "json"
    fields:
      - name: isOpen
        label: "Открыть заказы"
        type: boolean
        required: true
        default: false
      - name: message_en
        label: "Комментарий (EN)"
        type: text
      - name: message_ru
        label: "Комментарий (РУ)"
        type: text
  - name: prices
    label: "Прайсы"
    type: collection
    path: "content/prices"
    filename: "{primary}.json"
    format: "json"
    view: 
      fields: [ position, value ]
      default: { sort: value, order: desc }
      primary: position
      layout: tree
    fields:
      - name: position
        label: "Позиция"
        type: string
      - name: value
        label: "Цена"
        type: string
    
  # - name: pricelist
  #   label: "Прайсы"
  #   type: file
  #   path: "content/pricelist.json"
  #   format: "json"
  #   fields:
  #     - name: terms
  #       label: "Terms"
  #       type: rich-text
  #     - name: prices
  #       label: "Прайсы"
  #       type: block
  #       list: true
  #       blocks:
  #         - name: price
  #           label: "Прайс"
  #           fields:
  #             - name: title
  #               label: "Позиция"
  #               type: string
  #             - name: usd
  #               label: "$"
  #               type: number
  #         - name: percent
  #           label: "Процент"
  #           fields:
  #             - name: title
  #               label: "Позиция"
  #               type: string
  #             - name: percent
  #               label: "%"
  #               type: number
  #         - name: category
  #           label: "Категория"
  #           fields:
  #             - name: title
  #               label: "Название"
  #               type: string
  - name: socials
    label: "Соцсети"
    type: file
    path: "content/socials.json"
    format: "json"
    fields:
      - name: socials
        label: "Соцсети"
        type: block
        list: true
        blocks:
          - name: social
            label: "Соцсеть"
            fields:
              - name: title
                label: "Название"
                type: string
              - name: link
                label: "Ссылка"
                type: string